#ifndef QBEAGLEBONEBLACKGPIO_GLOBAL_H
#define QBEAGLEBONEBLACKGPIO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QBEAGLEBONEBLACKGPIO_LIBRARY)
#define QBEAGLEBONEBLACKGPIOSHARED_EXPORT Q_DECL_EXPORT
#else

#define QBEAGLEBONEBLACKGPIOSHARED_EXPORT Q_DECL_IMPORT

#endif

#endif // QBEAGLEBONEBLACKGPIO_GLOBAL_H
